//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeagueRecorder.Shared.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LeagueRecorder.Shared.Localization.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The chunk does not exist..
        /// </summary>
        public static string ChunkDoesNotExist {
            get {
                return ResourceManager.GetString("ChunkDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while deleting the chunk..
        /// </summary>
        public static string ErrorWhileDeletingChunk {
            get {
                return ResourceManager.GetString("ErrorWhileDeletingChunk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while deleting the keyframe..
        /// </summary>
        public static string ErrorWhileDeletingKeyFrame {
            get {
                return ResourceManager.GetString("ErrorWhileDeletingKeyFrame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The keyframe does not exist..
        /// </summary>
        public static string KeyFrameDoesNotExist {
            get {
                return ResourceManager.GetString("KeyFrameDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is currently no recording requested..
        /// </summary>
        public static string NoRecordingRequest {
            get {
                return ResourceManager.GetString("NoRecordingRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The rate limit was exceeded..
        /// </summary>
        public static string RateLimitExceeded {
            get {
                return ResourceManager.GetString("RateLimitExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The record does not exist..
        /// </summary>
        public static string RecordDoesNotExist {
            get {
                return ResourceManager.GetString("RecordDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The recording already exists..
        /// </summary>
        public static string RecordingAlreadyExists {
            get {
                return ResourceManager.GetString("RecordingAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The recording does not eixst..
        /// </summary>
        public static string RecordingDoesNotExist {
            get {
                return ResourceManager.GetString("RecordingDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to insert the recording..
        /// </summary>
        public static string RecordingInsertFailed {
            get {
                return ResourceManager.GetString("RecordingInsertFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The summoner was not found..
        /// </summary>
        public static string SummonerNotFound {
            get {
                return ResourceManager.GetString("SummonerNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The summoner is not ingame..
        /// </summary>
        public static string SummonerNotInGame {
            get {
                return ResourceManager.GetString("SummonerNotInGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected error..
        /// </summary>
        public static string UnexpectedError {
            get {
                return ResourceManager.GetString("UnexpectedError", resourceCulture);
            }
        }
    }
}
